In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
import copy

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.autograd import grad

from scipy.optimize import minimize

from Heston_NN import Net,weights_init

In [2]:
"""
1. Write a wrapper function.
out = model.forward(input)
2. Write a wrapper function for gradients

"""

'\n1. Write a wrapper function.\nout = model.forward(input)\n2. Write a wrapper function for gradients\n\n'

In [42]:
model = Net()
model.load_state_dict(torch.load('heston_NN'))
model = model.double()
model.eval() # evaluation mode

Net(
  (fc1): Linear(in_features=7, out_features=128, bias=True)
  (fc2): Linear(in_features=128, out_features=128, bias=True)
  (fc3): Linear(in_features=128, out_features=128, bias=True)
  (fc7): Linear(in_features=128, out_features=1, bias=True)
)

In [43]:
# First, we should have a dataset from a parameter set

In [62]:
inp = [np.double(np.random.uniform()) for i in range(7)]

In [64]:
inp_tensor=torch.tensor(inp, dtype=torch.double) # enforce datatype

In [65]:
model.forward(inp_tensor).detach().numpy()

array([0.08036388])

In [66]:
def model_wrapper(inp):
    out = model.forward(torch.tensor(inp)).detach().numpy()
    return out

In [67]:
model_wrapper(inp)

array([0.08036388])

In [69]:
res = minimize(model_wrapper,inp)

In [72]:
model_wrapper(res.x)

array([0.])