In [9]:
import torch
from torch import Tensor
from torch import autograd
from torch.autograd import grad
from torch import nn

In [10]:
def func(x):
    Q = (3*x**3).sum() # dQ = 9x**2 da
    return Q

In [11]:
a = torch.tensor([1.,2.0,3.0], requires_grad=True)
# Q = (3*a**3).sum() # dQ = 9a**2 da
Q = func(a)
dQda = grad(Q,a, create_graph = True)[0] # dQda = 9a**2
d2Qda2 = []
for i in range(len(a)):
    d2Qda2.append(grad(dQda[i],a, create_graph = True)[0][i]) # d2Qda2 = 18a
    
print('1st ',dQda)
print('2nd ',d2Qda2)

1st  tensor([ 9., 36., 81.], grad_fn=<MulBackward0>)
2nd  [tensor(18., grad_fn=<SelectBackward0>), tensor(36., grad_fn=<SelectBackward0>), tensor(54., grad_fn=<SelectBackward0>)]


In [12]:
torch.autograd.functional.jacobian(func, a)

tensor([ 9., 36., 81.])

In [13]:
torch.autograd.functional.hessian(func, a)

tensor([[18.,  0.,  0.],
        [ 0., 36.,  0.],
        [ 0.,  0., 54.]])

In [20]:
Q_cross = lambda x : x[0]*x[0]*x[1] + x[1]*x[1]*x[2] + x[2]*x[2]*x[0]
torch.autograd.functional.jacobian(Q_cross, a) # 2*x[0]*x[1] + 2*x[1]*x[2] + 2*x[2]*x[0]

In [24]:
torch.autograd.functional.hessian(Q_cross, a)

tensor([[4., 2., 6.],
        [2., 6., 4.],
        [6., 4., 2.]])